# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{grandstand}
  s.version = "0.2.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Flip Sasser"]
  s.date = %q{2010-11-10}
  s.description = %q{
      Grandstand is a simple blog and photo gallery application. It takes a minimal amount of configuration and can
      be built installed as a gem and used within minutes. It's totally cool. Seriously.
    }
  s.email = %q{flip@x451.com}
  s.extra_rdoc_files = [
    "README.markdown",
     "README.txt"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.markdown",
     "README.txt",
     "Rakefile",
     "VERSION",
     "app/controllers/galleries_controller.rb",
     "app/controllers/grandstand/galleries_controller.rb",
     "app/controllers/grandstand/images_controller.rb",
     "app/controllers/grandstand/main_controller.rb",
     "app/controllers/grandstand/pages_controller.rb",
     "app/controllers/grandstand/posts_controller.rb",
     "app/controllers/grandstand/sessions_controller.rb",
     "app/controllers/grandstand/templates_controller.rb",
     "app/controllers/grandstand/users_controller.rb",
     "app/controllers/pages_controller.rb",
     "app/controllers/posts_controller.rb",
     "app/helpers/galleries_helper.rb",
     "app/helpers/grandstand/galleries_helper.rb",
     "app/helpers/grandstand/images_helpers.rb",
     "app/helpers/grandstand/main_helper.rb",
     "app/helpers/grandstand/pages_helper.rb",
     "app/helpers/grandstand/posts_helper.rb",
     "app/helpers/grandstand/sessions_helper.rb",
     "app/helpers/grandstand/templates_helper.rb",
     "app/helpers/grandstand/users_helper.rb",
     "app/helpers/pages_helper.rb",
     "app/helpers/posts_helper.rb",
     "app/helpers/site_helper.rb",
     "app/models/grandstand/gallery.rb",
     "app/models/grandstand/image.rb",
     "app/models/grandstand/page.rb",
     "app/models/grandstand/page_section.rb",
     "app/models/grandstand/post.rb",
     "app/models/grandstand/template.rb",
     "app/models/grandstand/user.rb",
     "app/stylesheets/_buttons.less",
     "app/stylesheets/application.less",
     "app/stylesheets/global.less",
     "app/stylesheets/login.less",
     "app/stylesheets/wysiwyg.less",
     "app/views/galleries/index.html.erb",
     "app/views/galleries/show.html.erb",
     "app/views/grandstand/galleries/_form.html.erb",
     "app/views/grandstand/galleries/_gallery.html.erb",
     "app/views/grandstand/galleries/_list.html.erb",
     "app/views/grandstand/galleries/delete.html.erb",
     "app/views/grandstand/galleries/edit.html.erb",
     "app/views/grandstand/galleries/editor.html.erb",
     "app/views/grandstand/galleries/index.html.erb",
     "app/views/grandstand/galleries/new.html.erb",
     "app/views/grandstand/galleries/show.html.erb",
     "app/views/grandstand/images/_form.html.erb",
     "app/views/grandstand/images/delete.html.erb",
     "app/views/grandstand/images/edit.html.erb",
     "app/views/grandstand/images/new.html.erb",
     "app/views/grandstand/images/show.html.erb",
     "app/views/grandstand/images/upload.html.erb",
     "app/views/grandstand/main/index.html.erb",
     "app/views/grandstand/pages/_form.html.erb",
     "app/views/grandstand/pages/_left.html.erb",
     "app/views/grandstand/pages/_row.html.erb",
     "app/views/grandstand/pages/delete.html.erb",
     "app/views/grandstand/pages/edit.html.erb",
     "app/views/grandstand/pages/index.html.erb",
     "app/views/grandstand/pages/new.html.erb",
     "app/views/grandstand/pages/show.html.erb",
     "app/views/grandstand/posts/_form.html.erb",
     "app/views/grandstand/posts/_left.html.erb",
     "app/views/grandstand/posts/_list.html.erb",
     "app/views/grandstand/posts/delete.html.erb",
     "app/views/grandstand/posts/edit.html.erb",
     "app/views/grandstand/posts/index.html.erb",
     "app/views/grandstand/posts/new.html.erb",
     "app/views/grandstand/posts/preview.html.erb",
     "app/views/grandstand/posts/show.html.erb",
     "app/views/grandstand/sessions/forgot.html.erb",
     "app/views/grandstand/sessions/show.html.erb",
     "app/views/grandstand/shared/_flash.html.erb",
     "app/views/grandstand/users/_form.html.erb",
     "app/views/grandstand/users/_left.html.erb",
     "app/views/grandstand/users/delete.html.erb",
     "app/views/grandstand/users/edit.html.erb",
     "app/views/grandstand/users/index.html.erb",
     "app/views/grandstand/users/new.html.erb",
     "app/views/grandstand/users/show.html.erb",
     "app/views/layouts/grandstand.html.erb",
     "app/views/layouts/grandstand_login.html.erb",
     "app/views/layouts/grandstand_xhr.html.erb",
     "app/views/pages/show.html.erb",
     "app/views/posts/show.html.erb",
     "app/views/shared/404.html.erb",
     "app/views/shared/gallery.html",
     "app/views/shared/image.html",
     "app/views/shared/page.html",
     "app/views/shared/post.html",
     "config/routes.rb",
     "grandstand.gemspec",
     "lib/grandstand.rb",
     "lib/grandstand/application.rb",
     "lib/grandstand/controller.rb",
     "lib/grandstand/form_builder.rb",
     "lib/grandstand/helper.rb",
     "lib/grandstand/session.rb",
     "lib/grandstand/stylesheets_controller.rb",
     "pkg/grandstand-0.2.1.gem",
     "public/.DS_Store",
     "public/grandstand/images/background-input.gif",
     "public/grandstand/images/background-progress-bar.png",
     "public/grandstand/images/background-progress-complete.gif",
     "public/grandstand/images/background-progress.gif",
     "public/grandstand/images/galleries-empty.png",
     "public/grandstand/images/icons/add.png",
     "public/grandstand/images/icons/collapse.png",
     "public/grandstand/images/icons/delete.png",
     "public/grandstand/images/icons/edit.png",
     "public/grandstand/images/icons/editor/bold.png",
     "public/grandstand/images/icons/editor/gallery.png",
     "public/grandstand/images/icons/editor/image-center.png",
     "public/grandstand/images/icons/editor/image-left.png",
     "public/grandstand/images/icons/editor/image-right.png",
     "public/grandstand/images/icons/editor/image.png",
     "public/grandstand/images/icons/editor/italic.png",
     "public/grandstand/images/icons/editor/ordered-list.png",
     "public/grandstand/images/icons/editor/quote.png",
     "public/grandstand/images/icons/editor/source.png",
     "public/grandstand/images/icons/editor/strikethrough.png",
     "public/grandstand/images/icons/editor/underline.png",
     "public/grandstand/images/icons/editor/unordered-list.png",
     "public/grandstand/images/icons/error.png",
     "public/grandstand/images/icons/expand.png",
     "public/grandstand/images/icons/galleries.png",
     "public/grandstand/images/icons/gallery.png",
     "public/grandstand/images/icons/image.png",
     "public/grandstand/images/icons/okay.png",
     "public/grandstand/images/icons/pages.png",
     "public/grandstand/images/icons/posts.png",
     "public/grandstand/images/icons/processing.gif",
     "public/grandstand/images/icons/upload.png",
     "public/grandstand/images/icons/users.png",
     "public/grandstand/images/logo.png",
     "public/grandstand/images/spinner-dark.gif",
     "public/grandstand/images/uploader.swf",
     "public/grandstand/javascripts/application.js",
     "public/grandstand/javascripts/jquery.js",
     "public/grandstand/javascripts/mustache.js",
     "public/grandstand/javascripts/preview.js",
     "public/grandstand/javascripts/selection.js",
     "public/grandstand/javascripts/string.js",
     "public/grandstand/javascripts/wysiwyg.js",
     "public/grandstand/stylesheets/wysiwyg-content.css",
     "vendor/cache/more-0.1.1.gem"
  ]
  s.homepage = %q{http://github.com/flipsasser/grandstand}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A blog / gallery gem for Rails 3 that's dead-simple to configure, override, and rebuild}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<less>, [">= 1.2.21"])
      s.add_development_dependency(%q<more>, [">= 0.1.1"])
      s.add_runtime_dependency(%q<aws-s3>, [">= 0.6.2"])
      s.add_runtime_dependency(%q<mustache>, [">= 0.11.2"])
      s.add_runtime_dependency(%q<paperclip>, [">= 2.3.3"])
    else
      s.add_dependency(%q<less>, [">= 1.2.21"])
      s.add_dependency(%q<more>, [">= 0.1.1"])
      s.add_dependency(%q<aws-s3>, [">= 0.6.2"])
      s.add_dependency(%q<mustache>, [">= 0.11.2"])
      s.add_dependency(%q<paperclip>, [">= 2.3.3"])
    end
  else
    s.add_dependency(%q<less>, [">= 1.2.21"])
    s.add_dependency(%q<more>, [">= 0.1.1"])
    s.add_dependency(%q<aws-s3>, [">= 0.6.2"])
    s.add_dependency(%q<mustache>, [">= 0.11.2"])
    s.add_dependency(%q<paperclip>, [">= 2.3.3"])
  end
end

