# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{grandstand}
  s.version = "0.2.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Flip Sasser"]
  s.date = %q{2010-10-31}
  s.description = %q{
      Grandstand is a simple blog and photo gallery application. It takes a minimal amount of configuration and can
      be built installed as a gem and used within minutes. It's totally cool. Seriously.
    }
  s.email = %q{flip@x451.com}
  s.extra_rdoc_files = [
    "README.markdown",
     "README.txt"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.markdown",
     "README.txt",
     "Rakefile",
     "VERSION",
     "app/controllers/admin/galleries_controller.rb",
     "app/controllers/admin/images_controller.rb",
     "app/controllers/admin/main_controller.rb",
     "app/controllers/admin/pages_controller.rb",
     "app/controllers/admin/posts_controller.rb",
     "app/controllers/admin/sessions_controller.rb",
     "app/controllers/admin/templates_controller.rb",
     "app/controllers/admin/users_controller.rb",
     "app/controllers/galleries_controller.rb",
     "app/controllers/pages_controller.rb",
     "app/controllers/posts_controller.rb",
     "app/helpers/admin/galleries_helper.rb",
     "app/helpers/admin/images_helpers.rb",
     "app/helpers/admin/main_helper.rb",
     "app/helpers/admin/pages_helper.rb",
     "app/helpers/admin/posts_helper.rb",
     "app/helpers/admin/sessions_helper.rb",
     "app/helpers/admin/templates_helper.rb",
     "app/helpers/admin/users_helper.rb",
     "app/helpers/galleries_helper.rb",
     "app/helpers/pages_helper.rb",
     "app/helpers/posts_helper.rb",
     "app/helpers/site_helper.rb",
     "app/models/gallery.rb",
     "app/models/image.rb",
     "app/models/page.rb",
     "app/models/page_section.rb",
     "app/models/post.rb",
     "app/models/template.rb",
     "app/models/user.rb",
     "app/stylesheets/_buttons.less",
     "app/stylesheets/_dialogs.less",
     "app/stylesheets/application.less",
     "app/stylesheets/global.less",
     "app/stylesheets/login.less",
     "app/stylesheets/wysiwyg.less",
     "app/views/admin/galleries/_form.html.erb",
     "app/views/admin/galleries/_gallery.html.erb",
     "app/views/admin/galleries/_list.html.erb",
     "app/views/admin/galleries/delete.html.erb",
     "app/views/admin/galleries/edit.html.erb",
     "app/views/admin/galleries/editor.html.erb",
     "app/views/admin/galleries/editor_with_images.html.erb",
     "app/views/admin/galleries/index.html.erb",
     "app/views/admin/galleries/new.html.erb",
     "app/views/admin/galleries/show.html.erb",
     "app/views/admin/images/_form.html.erb",
     "app/views/admin/images/delete.html.erb",
     "app/views/admin/images/edit.html.erb",
     "app/views/admin/images/new.html.erb",
     "app/views/admin/images/upload.html.erb",
     "app/views/admin/main/index.html.erb",
     "app/views/admin/pages/_form.html.erb",
     "app/views/admin/pages/_left.html.erb",
     "app/views/admin/pages/_row.html.erb",
     "app/views/admin/pages/delete.html.erb",
     "app/views/admin/pages/edit.html.erb",
     "app/views/admin/pages/index.html.erb",
     "app/views/admin/pages/new.html.erb",
     "app/views/admin/pages/show.html.erb",
     "app/views/admin/posts/_form.html.erb",
     "app/views/admin/posts/_left.html.erb",
     "app/views/admin/posts/_list.html.erb",
     "app/views/admin/posts/delete.html.erb",
     "app/views/admin/posts/edit.html.erb",
     "app/views/admin/posts/index.html.erb",
     "app/views/admin/posts/new.html.erb",
     "app/views/admin/posts/show.html.erb",
     "app/views/admin/sessions/forgot.html.erb",
     "app/views/admin/sessions/show.html.erb",
     "app/views/admin/shared/_flash.html.erb",
     "app/views/admin/users/_form.html.erb",
     "app/views/admin/users/_left.html.erb",
     "app/views/admin/users/delete.html.erb",
     "app/views/admin/users/edit.html.erb",
     "app/views/admin/users/index.html.erb",
     "app/views/admin/users/new.html.erb",
     "app/views/admin/users/show.html.erb",
     "app/views/galleries/index.html.erb",
     "app/views/galleries/show.html.erb",
     "app/views/layouts/admin.html.erb",
     "app/views/layouts/grandstand_login.html.erb",
     "app/views/layouts/grandstand_xhr.html.erb",
     "app/views/pages/show.html.erb",
     "app/views/posts/show.html.erb",
     "app/views/shared/404.html.erb",
     "app/views/shared/gallery.html",
     "app/views/shared/image.html",
     "app/views/shared/page.html",
     "app/views/shared/post.html",
     "config/routes.rb",
     "db/migrate/20100220032742_create_galleries.rb",
     "db/migrate/20100220032824_create_images.rb",
     "db/migrate/20100220032911_create_users.rb",
     "db/migrate/20100615190000_create_posts.rb",
     "db/migrate/20100615190007_create_pages.rb",
     "db/migrate/20100615192132_create_page_sections.rb",
     "db/migrate/20100615193951_add_users_to_galleries_and_images.rb",
     "grandstand.gemspec",
     "lib/grandstand.rb",
     "lib/grandstand/application.rb",
     "lib/grandstand/controller.rb",
     "lib/grandstand/controller/development.rb",
     "lib/grandstand/helper.rb",
     "lib/grandstand/routes.rb",
     "lib/grandstand/session.rb",
     "pkg/grandstand-0.2.1.gem",
     "public/.DS_Store",
     "public/admin/.DS_Store",
     "public/admin/images/.DS_Store",
     "public/admin/images/background-input.gif",
     "public/admin/images/background-progress-bar.png",
     "public/admin/images/background-progress-complete.gif",
     "public/admin/images/background-progress.gif",
     "public/admin/images/icons/.DS_Store",
     "public/admin/images/icons/add.png",
     "public/admin/images/icons/collapse.png",
     "public/admin/images/icons/delete.png",
     "public/admin/images/icons/edit.png",
     "public/admin/images/icons/editor/bold.png",
     "public/admin/images/icons/editor/gallery.png",
     "public/admin/images/icons/editor/image-center.png",
     "public/admin/images/icons/editor/image-left.png",
     "public/admin/images/icons/editor/image-right.png",
     "public/admin/images/icons/editor/image.png",
     "public/admin/images/icons/editor/italic.png",
     "public/admin/images/icons/editor/ordered-list.png",
     "public/admin/images/icons/editor/quote.png",
     "public/admin/images/icons/editor/source.png",
     "public/admin/images/icons/editor/strikethrough.png",
     "public/admin/images/icons/editor/underline.png",
     "public/admin/images/icons/editor/unordered-list.png",
     "public/admin/images/icons/error.png",
     "public/admin/images/icons/expand.png",
     "public/admin/images/icons/galleries.png",
     "public/admin/images/icons/gallery.png",
     "public/admin/images/icons/image.png",
     "public/admin/images/icons/okay.png",
     "public/admin/images/icons/pages.png",
     "public/admin/images/icons/posts.png",
     "public/admin/images/icons/upload.png",
     "public/admin/images/icons/users.png",
     "public/admin/images/logo.png",
     "public/admin/images/spinner-dark.gif",
     "public/admin/images/uploader.swf",
     "public/admin/javascripts/application.js",
     "public/admin/javascripts/jquery.js",
     "public/admin/javascripts/mustache.js",
     "public/admin/javascripts/selection.js",
     "public/admin/javascripts/string.js",
     "public/admin/javascripts/wysiwyg.js",
     "public/admin/stylesheets/application.css",
     "public/admin/stylesheets/global.css",
     "public/admin/stylesheets/login.css",
     "public/admin/stylesheets/wysiwyg-content.css",
     "public/admin/stylesheets/wysiwyg.css",
     "vendor/cache/more-0.1.1.gem"
  ]
  s.homepage = %q{http://github.com/flipsasser/grandstand}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A blog / gallery gem for Rails 3 that's dead-simple to configure, override, and rebuild}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<less>, [">= 1.2.21"])
      s.add_runtime_dependency(%q<more>, [">= 0.1.1"])
      s.add_runtime_dependency(%q<aws-s3>, [">= 0.6.2"])
      s.add_runtime_dependency(%q<mustache>, [">= 0.11.2"])
      s.add_runtime_dependency(%q<paperclip>, [">= 2.3.3"])
    else
      s.add_dependency(%q<less>, [">= 1.2.21"])
      s.add_dependency(%q<more>, [">= 0.1.1"])
      s.add_dependency(%q<aws-s3>, [">= 0.6.2"])
      s.add_dependency(%q<mustache>, [">= 0.11.2"])
      s.add_dependency(%q<paperclip>, [">= 2.3.3"])
    end
  else
    s.add_dependency(%q<less>, [">= 1.2.21"])
    s.add_dependency(%q<more>, [">= 0.1.1"])
    s.add_dependency(%q<aws-s3>, [">= 0.6.2"])
    s.add_dependency(%q<mustache>, [">= 0.11.2"])
    s.add_dependency(%q<paperclip>, [">= 2.3.3"])
  end
end

